name: Slack Notification
on: [issues, gollum]
jobs:
  slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Issue
        if: ${{ github.event_name == 'issues' }}
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>
      - name: Wiki
        if: ${{ github.event_name == 'gollum' }}
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ toJson(github.event.pages) }}
